config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  get 'home/index'
  resources :dashboards, only: [] do
    collection do
      get :world_data
      get :world_map
      get :vaccination
      get :covid_chart
    end
  end

  resources :symptoms, only: [:index] do
    collection do
      get :diagnosis
    end
  end

  resources :potential_users do
    collection do
      post :import
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# Main Class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custom_log.rb
# frozen_string_literal: true

# Class for custom log
class CustomLog
  def self.debug(message = nil)
    @my_log ||= Logger.new("#{Rails.root}/log/email.log")
    @my_log.debug(message) unless message.nil?
  end
end

app/models/dashboard.rb
# frozen_string_literal: true

class Dashboard < ApplicationRecord
end

app/models/potential_user.rb
# frozen_string_literal: true

# Model for Potential User
class PotentialUser < ApplicationRecord
  def self.import(file)
    PotentialUser.destroy_all

    CSV.foreach(file.path, headers: true) do |row|
      PotentialUser.create! row.to_h
    end
  end

  def self.validate_email
    PotentialUser.all.map do |user|
      next unless Truemail.valid?(user.email)

      user.email
    end.compact
  end
end

app/models/symptom.rb
# frozen_string_literal: true

# Class for Symptoms
class Symptom < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

# Controller to handle covid dashboard actions
class DashboardsController < ApplicationController
  def world_data
    @world_data = ReportService.process_table_data('countries')
    @general_data = ReportService.process_table_data('all')
  rescue ReportService::ReportServiceError => e
    flash[:error] = e.message.to_s
  rescue StandardError => e
    flash[:error] = e.message.to_s
  end

  def vaccination
    @vaccination_data = ReportService.process_table_data('vaccine')
  rescue ReportService::ReportServiceError => e
    flash[:error] = e.message.to_s
  rescue StandardError => e
    flash[:error] = e.message.to_s
  end

  def covid_chart
    @area_chart = ReportService.process_area_chart_data('timeline')
    @bar_chart = ReportService.process_bar_chart_data('continents')
  rescue ReportService::ReportServiceError => e
    flash[:error] = e.message.to_s
  rescue StandardError => e
    flash[:error] = e.message.to_s
  end

  def world_map
    @covid_cases_map_data = ReportService.process_covid_map_data('countries', 'cases')
    @covid_death_map_data = ReportService.process_covid_map_data('countries', 'deaths')
  rescue ReportService::ReportServiceError => e
    flash[:error] = e.message.to_s
  rescue StandardError => e
    flash[:error] = e.message.to_s
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller to handle homepage actions
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/potential_users_controller.rb
# frozen_string_literal: true

# Controller to import potential users for mailing list
class PotentialUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: PotentialUserDatatable.new(params) }
    end
  end

  def import
    PotentialUser.import(params[:file])
    redirect_to potential_users_path, notice: 'File was successfully imported.'
  rescue StandardError => e
    redirect_to potential_users_path, notice: e.message.to_s
  end
end

app/controllers/symptoms_controller.rb
# frozen_string_literal: true

# Controller to handle symptom
class SymptomsController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: SymptomDatatable.new(params) }
    end
  end

  def diagnosis
    @diagnosis_data = ReportService.process_diagnosis_data(submit_params)
    return flash[:notice] = 'Here are the diagnosis for the symptoms' unless @diagnosis_data.blank?

    flash[:notice] = 'Invalid Input'
    redirect_to symptoms_path
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to symptoms_path
  end

  def submit_params
    params.permit(:symptoms, :gender, :year, :token)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module for application helper
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

# Helper for Dashboard
module DashboardsHelper
  def latest_update
    return if strip_latest_update_time.blank?

    Time.at(strip_latest_update_time).strftime('%d/%m/%Y')
  end

  def strip_latest_update_time
    @general_data&.dig('updated').to_s[0...-3].to_i
  end

  def world_data_top_section(value)
    number_with_delimiter(@general_data&.dig(value), delimiter: ',')
  end

  def vaccination_top_section(value)
    number_with_delimiter(@vaccination_data&.dig('OWID_WRL', value), delimiter: ',')
  end

  def area_chart_data(value)
    return [0] if @area_chart.blank?

    @area_chart[value]
  end

  def bar_chart_data(value)
    return [0] if @bar_chart.blank?

    @bar_chart[value]
  end
end

app/views/dashboards/covid_chart.html.erb
<div class="container-fluid  col-md-11 top-header">
	<div id="covid-area-chart"></div>
	<div id="covid-bar-chart"></div>
</div>

<script>
	Highcharts.chart('covid-area-chart', {
		chart: {
			type: 'areaspline'
		},
		title: {
			text: 'Total Cumulative Worldwide Cases (Since 2020-01-21)'
		},
		legend: {
			layout: 'vertical',
			align: 'left',
			verticalAlign: 'top',
			x: 150,
			y: 100,
			floating: true,
			borderWidth: 1,
			backgroundColor:
				Highcharts.defaultOptions.legend.backgroundColor || '#FFFFFF'
		},
		xAxis: {
			categories: <%= raw area_chart_data(:date) %>,
			plotBands: [{
				from: 4.5,
				to: 6.5,
				color: 'rgba(68, 170, 213, .2)'
			}]
		},
		yAxis: {
			title: {
				text: 'Number of Cases'
			}
		},
		tooltip: {
			shared: true,
		},
		credits: {
			enabled: false
		},
		plotOptions: {
			areaspline: {
				fillOpacity: 0.5
			}
		},
		series: [{
			name: 'recovered',
			data: <%= area_chart_data(:recovered) %>
		}, {
			name: 'deaths',
			data: <%= area_chart_data(:deaths) %>
		},{
			name: 'active',
			data: <%= area_chart_data(:active) %>
		}]
	});

	Highcharts.chart('covid-bar-chart', {
		chart: {
			type: 'bar'
		},
		title: {
			text: 'Covid-19 test per continent'
		},
		xAxis: {
			categories: <%= raw bar_chart_data(:continents) %>,
			title: {
				text: null
			}
		},
		yAxis: {
			min: 0,
			title: {
				text: 'Population (millions)',
				align: 'high'
			},
			labels: {
				overflow: 'justify'
			}
		},
		tooltip: {
			valueSuffix: ' millions'
		},
		plotOptions: {
			bar: {
				dataLabels: {
					enabled: true
				}
			}
		},
		legend: {
			layout: 'vertical',
			align: 'right',
			verticalAlign: 'top',
			x: -40,
			y: 80,
			floating: true,
			borderWidth: 1,
			backgroundColor:
				Highcharts.defaultOptions.legend.backgroundColor || '#FFFFFF',
			shadow: true
		},
		credits: {
			enabled: false
		},
		series: [{
			name: 'Population',
			data: <%= bar_chart_data(:population) %>
		}, {
			name: 'Number of Tests',
			data: <%= bar_chart_data(:tests) %>
		}]
	});
</script>

app/views/dashboards/vaccination.html.erb
<div class="container-fluid col-md-11">
	<div class="row top-header">
		<h6> <%= fa_icon "line-chart" %> Data on COVID-19 vaccinations about the Coronavirus Pandemic. </h6>
	</div>
	<br />
	<div class="row">
		<div class="col-md-3 vaccine-data">
			<%= fa_icon "plus-square" %>&nbsp;&nbsp;Total Vaccinations: <span class="positive"><%= vaccination_top_section('total_vaccinations') %></span>
		</div>
		<div class="col-md-3 vaccine-data">
			<%= fa_icon "users" %>&nbsp;&nbsp;Total Population: <span class="new-case"><%= vaccination_top_section('population') %></span>
		</div>
	</div>
	<br />
	<div class="row">
		<h6> <%= fa_icon "table" %> Reported Cases by Country, Territory, or Conveyance </h6>
	</div>
	<br />
	<table id="vaccine-data" class="table table-hover" %>
		<thead>
			<tr>
				<th>Continent</th>
				<th>Location</th>
				<th>New Vaccinations</th>
				<th>People Vaccinated</th>
				<th>People Fully Vaccinated</th>
				<th>Total Vaccinations</th>
				<th>New tests</th>
				<th>Total tests</th>
				<th>Population</th>
				<th>Median Age</th>
				<th>% Aged 65 Older</th>
				<th>% Aged 70 Older</th>
			</tr>
		</thead>
		<tbody>
			<% @vaccination_data&.each do |data| %>
			<tr>
				<td><%= data.second["continent"]%></td>
				<td><%= data.second["location"]%></td>
				<td class="positive"><%= number_with_delimiter("#{data.second["new_vaccinations"]}", delimiter: ',')%></td>
				<td class="favorable"><%= number_with_delimiter(data.second["people_vaccinated"], delimiter: ',')%></td>
				<td class="favorable"><%= number_with_delimiter(data.second["people_fully_vaccinated"], delimiter: ',')%></td>
				<td class="positive"><%= number_with_delimiter(data.second["total_vaccinations"], delimiter: ',')%></td>
				<td class="positive"><%= number_with_delimiter("#{data.second["new_tests"]}")%></td>
				<td class="favorable"><%= number_with_delimiter(data.second["total_tests"], delimiter: ',')%></td>
				<td><%= number_with_delimiter(data.second["population"], delimiter: ',')%></td>
				<td><%= number_with_delimiter(data.second["median_age"], delimiter: ',')%></td>
				<td><%= number_with_delimiter(data.second["aged_65_older"], delimiter: ',')%></td>
				<td><%= number_with_delimiter(data.second["aged_70_older"], delimiter: ',')%></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>


<script>
	$(document).ready(function() {
		$("#vaccine-data").dataTable({
			select: true,
			responsive: true,
			scrollX: true,
			dom: 'Bfrtip',
			buttons: [
				'copy', 'csv', 'excel', 'pdf', 'print'
			],
			order: [[ 1, "asc" ]]
		});
	});
</script>

app/views/dashboards/world_data.html.erb
<div class="container-fluid col-md-11">
  <div class="row top-header">
    <br />
    <h6> <%= fa_icon "line-chart" %> Data on COVID-19 vaccinations about the Coronavirus Pandemic. Last update: <%= latest_update %></h6>
  </div>
  <br />
  <div class="row">
    <div class="col-md-3 world-data">
      <%= fa_icon "ambulance" %>&nbsp;&nbsp;Currently Active: <span class="positive"><%= world_data_top_section('active') %></span>
    </div>
    <div class="col-md-3 world-data">
      <%= fa_icon "file" %>&nbsp;&nbsp;Total Confirmed: <span class="new-case"><%= world_data_top_section('cases') %></span>
    </div>
    <div class="col-md-3 world-data">
      <%= fa_icon "heartbeat" %>&nbsp;&nbsp;Total Recovered: <span class="favorable"><%= world_data_top_section('recovered') %></span>
    </div>
    <div class="col-md-3 world-data">
      <%= fa_icon "bed" %>&nbsp;&nbsp;Total Deaths: <span class="critical"><%= world_data_top_section('deaths') %></span>
    </div>
  </div>
  <br />
  <div class="row">
    <h6> <%= fa_icon "table" %> Reported Cases by Country, Territory, or Conveyance </h6>
  </div>
  <br />
  <table id="world-data" class="table table-hover" %>
    <thead>
      <tr>
        <th>Flags</th>
        <th>Codes</th>
        <th>Country</th>
        <th>New Cases</th>
        <th>New Deaths</th>
        <th>New recovered</th>
        <th>Active</th>
        <th>Critical</th>
        <th>Total Confirmed</th>
        <th>Total Recovered</th>
        <th>Total Deaths</th>
        <th>Total Tests</th>
        <th>Population</th>
      </tr>
    </thead>
    <tbody>
      <% @world_data&.each do |data| %>
      <tr>
        <td><%= image_tag(data['countryInfo']['flag'], height: '32', width: '32', alt: data['country'], delimiter: ',')%></td>
        <td><%= data['countryInfo']['iso3'] %></td>
        <td><%= data['country'] %></td>
        <td class="new-case"><%= number_with_delimiter("+#{data['todayCases']}", delimiter: ',')%></td>
        <td class="critical"><%= number_with_delimiter("+#{data['todayDeaths']}", delimiter: ',')%></td>
        <td class="favorable"><%= number_with_delimiter("+#{data['todayRecovered']}", delimiter: ',')%></td>
        <td class="positive"><%= number_with_delimiter(data['active'], delimiter: ',')%></td>
        <td class="critical"><%= number_with_delimiter(data['critical'], delimiter: ',')%></td>
        <td><%= number_with_delimiter(data['cases'], delimiter: ',')%></td>
        <td><%= number_with_delimiter(data['recovered'], delimiter: ',')%></td>
        <td><%= number_with_delimiter(data['deaths'], delimiter: ',')%></td>
        <td><%= number_with_delimiter(data['tests'], delimiter: ',')%></td>
        <td><%= number_with_delimiter(data['population'], delimiter: ',')%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>


<script>
  $(document).ready(function() {
    $("#world-data").dataTable({
      select: true,
      responsive: true,
      scrollX: true,
      dom: 'Bfrtip',
      buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
      ],
      order: [[ 3, "desc" ]]
    });
  });
</script>

app/views/dashboards/world_map.html.erb
<div class="container-fluid col-md-11 top-header">
	<div id="covid-cases"></div>
	<div id="covid-deaths"></div>
</div>

<script type="text/javascript">
	Highcharts.mapChart('covid-cases', {
		chart: {
			map: 'custom/world'
		},

		title: {
			text: 'Covid Cases'
		},

		mapNavigation: {
			enabled: true,
			enableDoubleClickZoomTo: true
		},

		colorAxis: {
			min: 1,
			max: 10000000,
			type: 'logarithmic'
		},

		series: [{
			data: <%= raw @covid_cases_map_data %>,
			joinBy: ['iso-a3', 'code3'],
			name: 'Covid Cases',
			states: {
				hover: {
					color: '#a4edba'
				}
			},
		}]
	});

	Highcharts.mapChart('covid-deaths', {
		chart: {
			map: 'custom/world'
		},

		title: {
			text: 'Covid Deaths'
		},

		mapNavigation: {
			enabled: true,
			enableDoubleClickZoomTo: true
		},

		colorAxis: {
			min: 1,
			max: 1000000,
			type: 'logarithmic',
			dataClasses: [{
				color: "#e1eb34",
				from: 1,
				to: 1000
			}, {
				color: "#ebba34",
				from: 1000,
				to: 10000
			}, {
				color: "#eb8034",
				from: 1000,
				to: 10000
			}, {
				color: "#eb5634",
				from: 10000,
				to: 100000
			}, {
				color: "#e30000",
				from: 100000,
				to: 1000000
			}]
		},

		series: [{
			data: <%= raw @covid_death_map_data %>,
			joinBy: ['iso-a3', 'code3'],
			name: 'Covid Death',
			states: {
				hover: {
					color: '#a4edba'
				}
			},
		}]
	});
</script>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>
<div class="container">
    <h1> WELCOME TO FLUFFY OCTO SYSTEM <h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FluffyOctoSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Highchart -->
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>
    <script src="https://code.highcharts.com/maps/modules/data.js"></script>
    <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/maps/modules/offline-exporting.js"></script>
    <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>

    <!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
    <link rel="stylesheet" type="text/css" href="//github.com/downloads/lafeber/world-flags-sprite/flags32.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('medical.ico') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/potential_users/index.html.erb
<div class="container-fluid col-md-10">
	<h4> Import Potential User Data </h4>
	<%= form_tag import_potential_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import from file' %>
	<% end %>

	<div class="col-md-6 table-section">
		<table id="potential-users-datatable" class="table table-hover" data-source="<%= potential_users_path(format: :json) %>">
			<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>


<script>
	$(document).ready(function() {
		$('#potential-users-datatable').dataTable({
			processing: true,
			serverSide: true,
			select: true,
			responsive: true,
			scrollX: true,
			dom: 'Bfrtip',
			buttons: [
				'copy', 'csv', 'excel', 'pdf', 'print'
			],
			ajax: {
				url: $('#potential-users-datatable').data('source')
			},
			pagingType: "full_numbers",
			columns: [{
				data: "id"
				},
				{
					data: "name"
				},
				{
					data: "email"
				},
			]
		});
	});
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon burger-button"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="navbar-brand" href="/"><%= image_tag('medical_nav.ico') %></a>
    <ul class="nav nav-navbar">
      <li class="nav-item">
        <%= fa_icon "medkit" %>&nbsp;<%= link_to "Active Cases", world_data_dashboards_path %>&nbsp;&nbsp;
      </li>
      &nbsp;&nbsp;
      <li class="nav-item">
        <%= fa_icon "stethoscope" %>&nbsp;<%= link_to "Vaccine Data", vaccination_dashboards_path %>&nbsp;&nbsp;
      </li>
      &nbsp;&nbsp;
      <li class="nav-item">
        <%= fa_icon "map-o" %>&nbsp;<%= link_to "Maps", world_map_dashboards_path %>&nbsp;&nbsp;
      </li>
      &nbsp;&nbsp;
      <li class="nav-item">
        <%= fa_icon "bar-chart" %>&nbsp;<%= link_to "Reports", covid_chart_dashboards_path %>&nbsp;&nbsp;
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= fa_icon "user-md" %>&nbsp;<%= link_to 'Diagnosis', symptoms_path %>&nbsp;&nbsp;
      </li>
      <li class="nav-item">
        <%= fa_icon "file" %>&nbsp;<%= link_to 'Potential Users', potential_users_path %>&nbsp;
      </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/symptoms/diagnosis.html.erb
<div class="container-fluid col-md-11">
  <table id="diagnosis-data" class="table table-hover" %>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Accuracy</th>
        <th>ICD</th>
        <th>ICD Name</th>
        <th>Prof Name</th>
        <th>Ranking</th>
        <th>Specialisation</th>
      </tr>
    </thead>
    <tbody>
      <% @diagnosis_data.each do |data| %>
      <tr>
        <td><%= data["Issue"]["ID"]%></td>
        <td><%= data["Issue"]["Name"]%></td>
        <td><%= data["Issue"]["Accuracy"]%></td>
        <td><%= data["Issue"]["Icd"]%></td>
        <td><%= data["Issue"]["IcdName"]%></td>
        <td><%= data["Issue"]["ProfName"]%></td>
        <td><%= data["Issue"]["Ranking"]%></td>
        <td><%= data["Specialisation"][0]["Name"]%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function() {
    $("#diagnosis-data").dataTable({
      select: true,
      responsive: true,
      scrollX: true,
      dom: 'Bfrtip',
      buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
      ]
    });
  });
</script>

app/views/symptoms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="container top-section">
      <form action="/symptoms/diagnosis" method="GET" class="form-horizontal custom-form">
        <div class="form-group">
          <label for="SymptomId">Symptom ID</label>
          <input class="form-control" type="text" name="symptoms" id="symptom-id" placeholder="10,20,30" required>
          <div class="invalid-feedback">
            Please provide Symptoms IDS.
          </div>
        </div>
        <div class="form-group">
          <label for="birthYear">Birth Year</label>
          <input class="form-control" type="text" name="year" id="birth-year" placeholder="29" required>
          <div class="invalid-feedback">
            Please provide your birth year.
          </div>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gender" id="gender-1" value="male" checked>
          <label class="form-check-label" for="gender-1">
            Male
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gender" id="gender-2" value="female">
          <label class="form-check-label" for="gender-2">
            Female
          </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
  <div class="col-md-6 table-section">
    <table id="symptoms-datatable" class="table table-hover" data-source="<%= symptoms_path(format: :json) %>">
      <thead>
        <tr>
          <th>ID</th>
          <th>Symptom ID</th>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>
</div>

<script>
  $(document).ready(function() {
    $('#symptoms-datatable').dataTable({
      processing: true,
      serverSide: true,
      select: true,
      responsive: true,
      scrollX: true,
      dom: 'Bfrtip',
      buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
      ],
      ajax: {
        url: $('#symptoms-datatable').data('source')
      },
      pagingType: "full_numbers",
      columns: [{
          data: "id"
        },
        {
          data: "symptom_id"
        },
        {
          data: "name"
        },
      ]
    });
  });
</script>